name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Setup integration testing environment
      run: |
        sudo apt-get -y install expect zbar-tools
        go run github.com/playwright-community/playwright-go/cmd/playwright install --with-deps
        go install filippo.io/age/cmd/...@latest

    - name: Test
      run: go test -v ./...
